use std::{f64::consts::PI,time::Instant};
use boon_lay::lagrangian_decay_simulator::lagrangian_diffusion::{central_limit_theorem::oorandom_rng::OoRng64,first_passage::interface::does_transmit};
use outram_mc_libs::rng::lcg::prn;
use uom::si::{diffusion_coefficient::square_meter_per_second,f64::DiffusionCoefficient};

const R:[f64;3]=[50e-6,75e-6,100e-6];const D:[f64;3]=[1e-9,2e-9,5e-9];const EPS:f64=100e-9;const ALPHA:f64=2.0;const N:usize=20_000;const TERMS:usize=2000;
const SS:[f64;6]=[0.,1.,2.,5.,10.,20.];const TT:[f64;6]=[0.02,0.05,0.10,0.20,0.40,0.80];

fn sr(x:f64,y:f64)->f64{if y.abs()<1e-7{x/y}else if y>700.{(x-y).exp()}else{x.sinh()/y.sinh()}}
fn ball_lt(r:f64,b:f64,d:f64,s:f64)->f64{if s==0.{return 1.}let l=(s/d).sqrt();if r==0.{let z=l*b;return if z>700.{0.}else{z/z.sinh()}}(b/r)*sr(l*r,l*b)}
fn shell_lt(a:f64,b:f64,r:f64,d:f64,s:f64)->(f64,f64){if s==0.{return(a*(b-r)/(r*(b-a)),b*(r-a)/(r*(b-a)))}let l=(s/d).sqrt();let den=l*(b-a);((a/r)*sr(l*(b-r),den),(b/r)*sr(l*(r-a),den))}
fn sample_t(seed:&mut u64,x:f64,l:f64,d:f64)->f64{let q=(x/l).powi(2);let sc=l*l/(d*PI*PI);let mut t=0.0;for n in 1..=TERMS{if prn(seed)>=q{t+=-prn(seed).max(f64::MIN_POSITIVE).ln()*sc/(n as f64).powi(2)}}t}
fn explicit(seed:u64)->f64{let mut g=OoRng64::from_u64(seed);let de=ALPHA*EPS;let mut layer=0usize;let mut r=R[0]*prn(&mut g.0).cbrt();let mut t=0.0;
 for _ in 0..1_000_000{if layer==0{t+=sample_t(&mut g.0,r,R[0],D[0]);let ok=does_transmit(&mut g.0,DiffusionCoefficient::new::<square_meter_per_second>(D[0]),DiffusionCoefficient::new::<square_meter_per_second>(D[1]),1.);if ok{layer=1;r=R[0]+de}else{r=R[0]-de}}
 else{let a=R[layer-1];let b=R[layer];let x=r-a;let po=b*x/(r*(b-a));let out=prn(&mut g.0)<po;let y=if out{x}else{b-r};t+=sample_t(&mut g.0,y,b-a,D[layer]);if layer==2&&out{return t}let next=if out{layer+1}else{layer-1};let ok=does_transmit(&mut g.0,DiffusionCoefficient::new::<square_meter_per_second>(D[layer]),DiffusionCoefficient::new::<square_meter_per_second>(D[next]),1.);if ok{layer=next;r=if out{a+(b-a)+de}else{a-de}}else{r=if out{b-de}else{a+de}}}}panic!("cap")}
fn matrix(s:f64)->([[f64;4];4],[f64;4]){let de=ALPHA*EPS;let mut k=[[0.0;4];4];let mut b=[0.0;4];let p=|i:usize,j:usize|D[j]/(D[i]+D[j]);
 let h=ball_lt(R[0]-de,R[0],D[0],s);k[0][0]=h*(1.0-p(0,1));k[0][1]=h*p(0,1);
 for (st,r) in [(1,R[0]+de),(2,R[1]-de)]{let(gm,gp)=shell_lt(R[0],R[1],r,D[1],s);k[st][0]=gm*p(1,0);k[st][1]=gm*(1.0-p(1,0));k[st][2]=gp*(1.0-p(1,2));k[st][3]=gp*p(1,2);}
 let(gm,gp)=shell_lt(R[1],R[2],R[1]+de,D[2],s);k[3][2]=gm*p(2,1);k[3][3]=gm*(1.0-p(2,1));b[3]=gp;(k,b)}
fn solve(mut a:[[f64;4];4],mut b:[f64;4])->[f64;4]{for i in 0..4{let mut m=i;for j in i+1..4{if a[j][i].abs()>a[m][i].abs(){m=j}}a.swap(i,m);b.swap(i,m);let p=a[i][i];for j in i..4{a[i][j]/=p}b[i]/=p;for r in 0..4{if r!=i{let f=a[r][i];for j in i..4{a[r][j]-=f*a[i][j]}b[r]-=f*b[i]}}}b}
fn phi(s:f64)->([f64;4],f64,f64){let(k,b)=matrix(s);let mut a=[[0.0;4];4];for i in 0..4{for j in 0..4{a[i][j]=(if i==j{1.}else{0.})-k[i][j]}}let x=solve(a,b);let mut res=0.0;for i in 0..4{let mut z=-b[i];for j in 0..4{z+=a[i][j]*x[j]}res+=z*z} // Frobenius bound condition via ||A||F ||A^-1||F
 let mut inv=[[0.0;4];4];for j in 0..4{let mut e=[0.0;4];e[j]=1.0;let col=solve(a,e);for i in 0..4{inv[i][j]=col[i]}}let nf=a.iter().flatten().map(|x|x*x).sum::<f64>().sqrt();let ni=inv.iter().flatten().map(|x|x*x).sum::<f64>().sqrt();(x,nf*ni,res.sqrt())}
fn init_phi(s:f64,x:[f64;4])->f64{let q=(1.0-D[1]/(D[0]+D[1]))*x[0]+D[1]/(D[0]+D[1])*x[1];if s==0.{return q}let n=20000;let dr=R[0]/n as f64;let mut z=0.0;for i in 0..n{let r=(i as f64+0.5)*dr;z+=3.0*r*r/R[0].powi(3)*ball_lt(r,R[0],D[0],s)}z*dr*q}
fn vol(a:f64,b:f64)->f64{4.0*PI/3.0*(b.powi(3)-a.powi(3))}fn cent(a:f64,b:f64)->f64{0.75*(b.powi(4)-a.powi(4))/(b.powi(3)-a.powi(3))}
fn fv(npl:usize,q:f64)->(Vec<f64>,f64,f64){let mut f=vec![0.];for l in 0..3{for j in 1..=npl{f.push(R[l-0]*(j as f64/npl as f64) + if l==0{0.}else{R[l-1]*(1.0-j as f64/npl as f64)})}} // aligned equal layer widths
 let n=f.len()-1;let rc:Vec<f64>=(0..n).map(|i|cent(f[i],f[i+1])).collect();let vv:Vec<f64>=(0..n).map(|i|vol(f[i],f[i+1])).collect();let dd:Vec<f64>=rc.iter().map(|&r|if r<R[0]{D[0]}else if r<R[1]{D[1]}else{D[2]}).collect();let mut g=vec![0.0;n-1];for i in 0..n-1{let rf=f[i+1];g[i]=4.0*PI*rf*rf/((rf-rc[i])/dd[i]+(rc[i+1]-rf)/dd[i+1])}let gr=4.0*PI*R[2]*R[2]*D[2]/(R[2]-rc[n-1]);let mut dt=f64::INFINITY;for i in 0..n{let gw=if i==0{0.}else{g[i-1]};let ge=if i==n-1{gr}else{g[i]};dt=dt.min(vv[i]/(gw+ge))}dt*=q;let v0=vol(0.,R[0]);let mut c:Vec<f64>=(0..n).map(|i|if f[i+1]<=R[0]*(1.0+1e-12){1./v0}else{0.}).collect();let mut nx=vec![0.0;n];let mut t=0.0;let mut rel=0.0;let mut out=Vec::new();let mut k=0;let mut cons=0f64;while k<TT.len(){if t>=TT[k]-1e-15{out.push(rel);k+=1;continue}let h=dt.min(TT[k]-t);let old:f64=c.iter().zip(&vv).map(|(x,v)|x*v).sum();let qr=gr*c[n-1];for i in 0..n{let gw=if i==0{0.}else{g[i-1]};let ge=if i==n-1{gr}else{g[i]};let w=if i==0{0.}else{c[i-1]};let e=if i==n-1{0.}else{c[i+1]};nx[i]=c[i]+h/vv[i]*(gw*w-(gw+ge)*c[i]+if i==n-1{0.}else{ge*e})}let new:f64=nx.iter().zip(&vv).map(|(x,v)|x*v).sum();rel+=h*qr;cons=cons.max((new-old+h*qr).abs());std::mem::swap(&mut c,&mut nx);t+=h}(out,dt,cons)}
fn main(){println!("THREE_LAYER_MULTISTATE R={R:?} D={D:?} N={N} s={SS:?} t={TT:?}");let start=Instant::now();let times:Vec<f64>=(0..N).map(|i|explicit(0x3A11_0000+i as u64)).collect();
 for &s in &SS{let(x,cond,res)=phi(s);let m=init_phi(s,x);let vals:Vec<f64>=times.iter().map(|&t|(-s*t).exp()).collect();let em=vals.iter().sum::<f64>()/N as f64;let var=vals.iter().map(|v|(v-em).powi(2)).sum::<f64>()/(N-1)as f64;let se=(var/N as f64).sqrt();println!("TRANS s={s:.3} states={x:?} matrix={m:.12e} explicit={em:.12e} se={se:.12e} delta={:.12e} z={:.6} condF={cond:.6e} residual={res:.3e}",em-m,if se>0.{(em-m)/se}else{0.});}
 for &t in &TT{let n=times.iter().filter(|&&x|x<=t).count();let p=n as f64/N as f64;println!("CDF t={t:.3} B={p:.8} se={:.8}",(p*(1.0-p)/N as f64).sqrt())}
 for n in [50usize,100,200]{let(f,dt,cons)=fv(n,0.4);println!("FV spatial npl={n} dt={dt:.6e} cons={cons:.3e} F={f:?}")}
 let(f1,dt1,c1)=fv(200,0.4);let(f2,dt2,c2)=fv(200,0.2);let md=f1.iter().zip(&f2).map(|(a,b)|(a-b).abs()).fold(0f64,f64::max);println!("FV temporal dt1={dt1:.6e} dt2={dt2:.6e} maxdiff={md:.6e} cons1={c1:.3e} cons2={c2:.3e} fine={f2:?} elapsed={:.3}",start.elapsed().as_secs_f64());}